name: 'Get Run Metadata'
description: 'Get various metadata about the run'
branding:
  icon: 'book'
  color: 'green'
outputs:
  url:
    description: "Direct HTML link to check page"
  id:
    description: "ID of the check suite"
  pr:
    description: "The PR number"
  started_at:
    description: "The time the run started"
  head_sha:
    description: "The HEAD hash"
  head_sha7:
    description: "SHA7 version of the HEAD hash"
  head_sha8:
    description: "SHA8 version of the HEAD hash"
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.GITHUB_TOKEN }}
